// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Account
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Account
    {
        public int AcountId { get; set; } // AcountId (Primary key)

        ///<summary>
        /// دوره
        ///</summary>
        public int TermId { get; set; } // TermId

        ///<summary>
        /// تاریخ صورت حساب
        ///</summary>
        public System.DateTime BillDate { get; set; } // BillDate

        ///<summary>
        /// شرح
        ///</summary>
        public string Description { get; set; } // Description (length: 150)

        ///<summary>
        /// تعداد اقلام
        ///</summary>
        public int? Count { get; set; } // Count

        ///<summary>
        /// هزینه پایه
        ///</summary>
        public int? BaseCharge { get; set; } // BaseCharge

        ///<summary>
        /// مبلغ طلبکار
        ///</summary>
        public int? Creditor { get; set; } // Creditor

        ///<summary>
        /// مبلغ بدهکار
        ///</summary>
        public int? Debtor { get; set; } // Debtor

        ///<summary>
        /// جزئیات دارد؟
        ///</summary>
        public bool IsDetailed { get; set; } // IsDetailed
    }

}
// </auto-generated>
