// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // AwardConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AwardConfig
    {
        public int AwardConfigId { get; set; } // AwardConfigId (Primary key)

        ///<summary>
        /// مربوط به عنوان امتیاز
        ///</summary>
        public int ScoreItemId { get; set; } // ScoreItemId
        public int TermId { get; set; } // TermId
        public decimal Score { get; set; } // Score

        ///<summary>
        /// میزان تاخیر
        ///</summary>
        public int Delay { get; set; } // Delay
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [AwardConfig].([RecordStatusId]) (FK_AwardConfig_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_AwardConfig_GeneralBaseType
        /// <summary>
        /// Parent ScoreItem pointed by [AwardConfig].([ScoreItemId]) (FK_AwardConfig_ScoreItem)
        /// </summary>
        public virtual ScoreItem ScoreItem { get; set; } // FK_AwardConfig_ScoreItem
        /// <summary>
        /// Parent Term pointed by [AwardConfig].([TermId]) (FK_AwardConfig_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_AwardConfig_Term
    }

}
// </auto-generated>
