// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // AwardScore
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AwardScore
    {
        public int AwardScoreId { get; set; } // AwardScoreId (Primary key)
        public int AwardId { get; set; } // AwardId
        public int Score { get; set; } // Score
        public int TermId { get; set; } // TermId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child StudentAwards where [StudentAward].[AwardScoreId] point to this entity (FK_StudentAward_AwardScore)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentAward> StudentAwards { get; set; } // StudentAward.FK_StudentAward_AwardScore

        // Foreign keys

        /// <summary>
        /// Parent Award pointed by [AwardScore].([AwardId]) (FK_AwardScore_Award)
        /// </summary>
        public virtual Award Award { get; set; } // FK_AwardScore_Award
        /// <summary>
        /// Parent GeneralBaseType pointed by [AwardScore].([RecordStatusId]) (FK_AwardScore_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_AwardScore_GeneralBaseType
        /// <summary>
        /// Parent Term pointed by [AwardScore].([TermId]) (FK_AwardScore_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_AwardScore_Term

        public AwardScore()
        {
            StudentAwards = new System.Collections.Generic.List<StudentAward>();
        }
    }

}
// </auto-generated>
