// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Camp
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Camp
    {
        public int CampId { get; set; } // CampId (Primary key)

        ///<summary>
        /// جلسه اردو
        ///</summary>
        public int ClassSessionId { get; set; } // ClassSessionId

        ///<summary>
        /// اردو خانوادگی
        ///</summary>
        public bool Domestic { get; set; } // Domestic

        ///<summary>
        /// مکان اردو
        ///</summary>
        public int PlaceId { get; set; } // PlaceId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent ClassSession pointed by [Camp].([ClassSessionId]) (FK_Camp_ClassSession)
        /// </summary>
        public virtual ClassSession ClassSession { get; set; } // FK_Camp_ClassSession
        /// <summary>
        /// Parent GeneralBaseType pointed by [Camp].([RecordStatusId]) (FK_Camp_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_Camp_GeneralBaseType
        /// <summary>
        /// Parent Place pointed by [Camp].([PlaceId]) (FK_Camp_Place)
        /// </summary>
        public virtual Place Place { get; set; } // FK_Camp_Place

        public Camp()
        {
            Domestic = false;
        }
    }

}
// </auto-generated>
