// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // ClassScadule
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class ClassScadule
    {
        public int ClassScaduleId { get; set; } // ClassScaduleId (Primary key)
        public int ClassId { get; set; } // ClassId

        ///<summary>
        /// هفتگی یا روزانه
        ///</summary>
        public int ScaduleTypeId { get; set; } // ScaduleTypeId
        public System.DateTime? Date { get; set; } // Date
        public int? DayId { get; set; } // DayId
        public System.TimeSpan StartTime { get; set; } // StartTime
        public System.TimeSpan EndTime { get; set; } // EndTime
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child ClassSessions where [ClassSession].[ClassScaduleId] point to this entity (FK_ClassSession_ClassScadule)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassSession> ClassSessions { get; set; } // ClassSession.FK_ClassSession_ClassScadule

        // Foreign keys

        /// <summary>
        /// Parent Class pointed by [ClassScadule].([ClassId]) (FK_ClassScadule_Class)
        /// </summary>
        public virtual Class Class { get; set; } // FK_ClassScadule_Class
        /// <summary>
        /// Parent GeneralBaseType pointed by [ClassScadule].([RecordStatusId]) (FK_ClassScadule_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_ClassScadule_GeneralBaseType1
        /// <summary>
        /// Parent GeneralBaseType pointed by [ClassScadule].([ScaduleTypeId]) (FK_ClassScadule_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType ScaduleType { get; set; } // FK_ClassScadule_GeneralBaseType

        public ClassScadule()
        {
            ClassSessions = new System.Collections.Generic.List<ClassSession>();
        }
    }

}
// </auto-generated>
