// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // DocumentTag
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class DocumentTag
    {
        public int DocumentTagId { get; set; } // DocumentTagId (Primary key)
        public int TagId { get; set; } // TagId
        public int DocumentId { get; set; } // DocumentId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent Document pointed by [DocumentTag].([DocumentId]) (FK_DocumentTag_Document)
        /// </summary>
        public virtual Document Document { get; set; } // FK_DocumentTag_Document
        /// <summary>
        /// Parent GeneralBaseType pointed by [DocumentTag].([RecordStatusId]) (FK_DocumentTag_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_DocumentTag_GeneralBaseType
        /// <summary>
        /// Parent Tag pointed by [DocumentTag].([TagId]) (FK_DocumentTag_Tag)
        /// </summary>
        public virtual Tag Tag { get; set; } // FK_DocumentTag_Tag
    }

}
// </auto-generated>
