// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Festival
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Festival
    {
        public int FestivalId { get; set; } // FestivalId (Primary key)
        public string Name { get; set; } // Name (length: 30)
        public string Description { get; set; } // Description (length: 100)
        public int ClassSessionId { get; set; } // ClassSessionId

        ///<summary>
        /// رتبه اول
        ///</summary>
        public int? FirstPlaceId { get; set; } // FirstPlaceId

        ///<summary>
        /// رتبه دوم
        ///</summary>
        public int? SecondPlaceId { get; set; } // SecondPlaceId

        ///<summary>
        /// رتبه سوم
        ///</summary>
        public int? ThirdPlaceId { get; set; } // ThirdPlaceId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent ClassSession pointed by [Festival].([ClassSessionId]) (FK_Festival_ClassSession)
        /// </summary>
        public virtual ClassSession ClassSession { get; set; } // FK_Festival_ClassSession
        /// <summary>
        /// Parent GeneralBaseType pointed by [Festival].([RecordStatusId]) (FK_Festival_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_Festival_GeneralBaseType
        /// <summary>
        /// Parent Student pointed by [Festival].([FirstPlaceId]) (FK_Festival_Student)
        /// </summary>
        public virtual Student FirstPlace { get; set; } // FK_Festival_Student
        /// <summary>
        /// Parent Student pointed by [Festival].([SecondPlaceId]) (FK_Festival_Student1)
        /// </summary>
        public virtual Student SecondPlace { get; set; } // FK_Festival_Student1
        /// <summary>
        /// Parent Student pointed by [Festival].([ThirdPlaceId]) (FK_Festival_Student2)
        /// </summary>
        public virtual Student ThirdPlace { get; set; } // FK_Festival_Student2
    }

}
// </auto-generated>
