// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // GeneralBaseCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class GeneralBaseCategory
    {
        public int GeneralBaseCategoryId { get; set; } // GeneralBaseCategoryId (Primary key)

        ///<summary>
        /// عنوان انگلیسی
        ///</summary>
        public string Name { get; set; } // Name (length: 30)

        ///<summary>
        /// عنوان فارسی
        ///</summary>
        public string Title { get; set; } // Title (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child GeneralBaseTypes where [GeneralBaseType].[GeneralBaseCategoryId] point to this entity (FK_GeneralBaseType_GeneralBaseCategory)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<GeneralBaseType> GeneralBaseTypes { get; set; } // GeneralBaseType.FK_GeneralBaseType_GeneralBaseCategory

        public GeneralBaseCategory()
        {
            GeneralBaseTypes = new System.Collections.Generic.List<GeneralBaseType>();
        }
    }

}
// </auto-generated>
