// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Group
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Group
    {
        public int GroupId { get; set; } // GroupId (Primary key)
        public int TermId { get; set; } // TermId
        public string Name { get; set; } // Name (length: 30)
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child Classes where [Class].[GroupId] point to this entity (FK_Class_Group)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> Classes { get; set; } // Class.FK_Class_Group
        /// <summary>
        /// Child GroupStudents where [GroupStudent].[GroupId] point to this entity (FK_GroupStudent_GroupStudent)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<GroupStudent> GroupStudents { get; set; } // GroupStudent.FK_GroupStudent_GroupStudent

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Group].([RecordStatusId]) (FK_Group_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_Group_GeneralBaseType
        /// <summary>
        /// Parent Term pointed by [Group].([TermId]) (FK_Group_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_Group_Term

        public Group()
        {
            Classes = new System.Collections.Generic.List<Class>();
            GroupStudents = new System.Collections.Generic.List<GroupStudent>();
        }
    }

}
// </auto-generated>
