// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;
    using System.ComponentModel;

    // Parent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Parent
    {
        [DisplayName("شماره")]
        public int ParentId { get; set; } // ParentId (Primary key)
        [DisplayName("نام")]
        public string FirstName { get; set; } // FirstName (length: 30)
        [DisplayName("نام خانوادگی")]
        public string LastName { get; set; } // LastName (length: 50)
        public string Job { get; set; } // Job (length: 30)

        ///<summary>
        /// مواردی که می توانند به پایگاه کمک کنند
        ///</summary>
        public string AssistantContext { get; set; } // AssistantContext (length: 50)
        public int StudentId { get; set; } // StudentId
        public bool WithoutParent { get; set; } // WithoutParent
        public int RelationshipId { get; set; } // RelationshipId
        public string Email { get; set; } // Email (length: 50)
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[ParentId] point to this entity (FK_PhoneNumber_Parent)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> PhoneNumbers { get; set; } // PhoneNumber.FK_PhoneNumber_Parent
        /// <summary>
        /// Child RollCalls where [RollCall].[ParentId] point to this entity (FK_RollCall_Parent)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RollCall> RollCalls { get; set; } // RollCall.FK_RollCall_Parent

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Parent].([RecordStatusId]) (FK_Parent_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_Parent_GeneralBaseType1
        /// <summary>
        /// Parent GeneralBaseType pointed by [Parent].([RelationshipId]) (FK_Parent_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType Relationship { get; set; } // FK_Parent_GeneralBaseType
        /// <summary>
        /// Parent Student pointed by [Parent].([StudentId]) (FK_Parent_Student)
        /// </summary>
        public virtual Student Student { get; set; } // FK_Parent_Student

        public Parent()
        {
            WithoutParent = false;
            PhoneNumbers = new System.Collections.Generic.List<PhoneNumber>();
            RollCalls = new System.Collections.Generic.List<RollCall>();
        }
    }

}
// </auto-generated>
