// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    using Mapping;

    // Permission
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Permission : Infra.Wpf.Repository.ModelBase<Permission>
    {
        [Column(@"PermmisionId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int PermmisionId { get { return Get<int>(); } set { Set(value); } } // PermmisionId (Primary key)

        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "دسترسی")]
        public string Title { get { return Get<string>(); } set { Set(value); } } // Title (length: 50)

        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Url]
        public string Url { get { return Get<string>(); } set { Set(value); } } // Url (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child RolePermissions where [RolePermission].[PermissionId] point to this entity (FK_RolePermission_Permission)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RolePermission> RolePermissions { get; set; } // RolePermission.FK_RolePermission_Permission

        public Permission()
        {
            RolePermissions = new System.Collections.Generic.List<RolePermission>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
