// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // PhoneNumber
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class PhoneNumber
    {
        public int PhoneNumberId { get; set; } // PhoneNumberId (Primary key)
        public int? StudentId { get; set; } // StudentId
        public int? ParentId { get; set; } // ParentId
        public int? TeacherId { get; set; } // TeacherId

        ///<summary>
        /// شماره تلفن متعلق به کیست (معلم، دانش آموز، والدین)
        ///</summary>
        public int OwnerId { get; set; } // OwnerId
        public int PhoneNumber_ { get; set; } // PhoneNumber

        ///<summary>
        /// خانه، کار، موبایل
        ///</summary>
        public int PhoneNumberTypeId { get; set; } // PhoneNumberTypeId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [PhoneNumber].([OwnerId]) (FK_PhoneNumber_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType Owner { get; set; } // FK_PhoneNumber_GeneralBaseType
        /// <summary>
        /// Parent GeneralBaseType pointed by [PhoneNumber].([PhoneNumberTypeId]) (FK_PhoneNumber_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType PhoneNumberType { get; set; } // FK_PhoneNumber_GeneralBaseType1
        /// <summary>
        /// Parent GeneralBaseType pointed by [PhoneNumber].([RecordStatusId]) (FK_PhoneNumber_GeneralBaseType2)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_PhoneNumber_GeneralBaseType2
        /// <summary>
        /// Parent Parent pointed by [PhoneNumber].([ParentId]) (FK_PhoneNumber_Parent)
        /// </summary>
        public virtual Parent Parent { get; set; } // FK_PhoneNumber_Parent
        /// <summary>
        /// Parent Student pointed by [PhoneNumber].([StudentId]) (FK_PhoneNumber_Student)
        /// </summary>
        public virtual Student Student { get; set; } // FK_PhoneNumber_Student
        /// <summary>
        /// Parent Teacher pointed by [PhoneNumber].([TeacherId]) (FK_PhoneNumber_Teacher)
        /// </summary>
        public virtual Teacher Teacher { get; set; } // FK_PhoneNumber_Teacher
    }

}
// </auto-generated>
