// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // RolePermission
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class RolePermission
    {
        public int RolePermissionId { get; set; } // RolePermissionId (Primary key)
        public int RoleId { get; set; } // RoleId
        public int PermissionId { get; set; } // PermissionId

        // Foreign keys

        /// <summary>
        /// Parent Permission pointed by [RolePermission].([PermissionId]) (FK_RolePermission_Permission)
        /// </summary>
        public virtual Permission Permission { get; set; } // FK_RolePermission_Permission
        /// <summary>
        /// Parent Role pointed by [RolePermission].([RoleId]) (FK_RolePermission_Role)
        /// </summary>
        public virtual Role Role { get; set; } // FK_RolePermission_Role
    }

}
// </auto-generated>
