// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    using Mapping;

    // SettleDebtDemand
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class SettleDebtDemand
    {
        [Column(@"SettleDebtDemandId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int SettleDebtDemandId { get; set; } // SettleDebtDemandId (Primary key)

        [Required]
        public int TransactionId { get; set; } // TransactionId

        [Required]
        public int DebtDemandId { get; set; } // DebtDemandId

        // Foreign keys

        /// <summary>
        /// Parent DebtDemand pointed by [SettleDebtDemand].([DebtDemandId]) (FK_SettleDebtDemand_DebtDemand)
        /// </summary>
        public virtual DebtDemand DebtDemand { get; set; } // FK_SettleDebtDemand_DebtDemand

        /// <summary>
        /// Parent Transaction pointed by [SettleDebtDemand].([TransactionId]) (FK_SettleDebtDemand_Transaction)
        /// </summary>
        public virtual Transaction Transaction { get; set; } // FK_SettleDebtDemand_Transaction

        public SettleDebtDemand()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
