// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // StudentClass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class StudentClass
    {
        public int StudentClassId { get; set; } // StudentClassId (Primary key)
        public int ClassId { get; set; } // ClassId
        public int StudentId { get; set; } // StudentId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent Class pointed by [StudentClass].([ClassId]) (FK_StudentClass_Class)
        /// </summary>
        public virtual Class Class { get; set; } // FK_StudentClass_Class
        /// <summary>
        /// Parent GeneralBaseType pointed by [StudentClass].([RecordStatusId]) (FK_StudentClass_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_StudentClass_GeneralBaseType
        /// <summary>
        /// Parent Student pointed by [StudentClass].([StudentId]) (FK_StudentClass_Student)
        /// </summary>
        public virtual Student Student { get; set; } // FK_StudentClass_Student
    }

}
// </auto-generated>
