// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;
    using System.ComponentModel;

    // Student
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Student
    {
        [DisplayName("شماره")]
        public int StudentId { get; set; } // StudentId (Primary key)
        [DisplayName("نام")]
        public string FirstName { get; set; } // FirstName (length: 30)
        [DisplayName("نام خانوادگی")]
        public string LastName { get; set; } // LastName (length: 50)
        [DisplayName("تاریخ تولد")]
        public System.DateTime? Birthday { get; set; } // Birthday

        ///<summary>
        /// کدملی
        ///</summary>
        public int? NationalCode { get; set; } // NationalCode

        ///<summary>
        /// شماره شناسنامه
        ///</summary>
        public int? IdentifiereNo { get; set; } // IdentifiereNo
        public byte[] Picture { get; set; } // Picture (length: 2147483647)
        public int? BasijStatusId { get; set; } // BasijStatusId
        public string Address { get; set; } // Address (length: 200)
        public string Email { get; set; } // Email (length: 50)
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child ClassPoints where [ClassPoint].[StudentId] point to this entity (FK_ClassPoint_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassPoint> ClassPoints { get; set; } // ClassPoint.FK_ClassPoint_Student
        /// <summary>
        /// Child ClassScores where [ClassScore].[StudentId] point to this entity (FK_ClassScore_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassScore> ClassScores { get; set; } // ClassScore.FK_ClassScore_Student
        /// <summary>
        /// Child Festivals where [Festival].[FirstPlaceId] point to this entity (FK_Festival_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Festival> FirstPlace { get; set; } // Festival.FK_Festival_Student
        /// <summary>
        /// Child Festivals where [Festival].[SecondPlaceId] point to this entity (FK_Festival_Student1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Festival> SecondPlace { get; set; } // Festival.FK_Festival_Student1
        /// <summary>
        /// Child Festivals where [Festival].[ThirdPlaceId] point to this entity (FK_Festival_Student2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Festival> ThirdPlace { get; set; } // Festival.FK_Festival_Student2
        /// <summary>
        /// Child GroupStudents where [GroupStudent].[StudentId] point to this entity (FK_GroupStudent_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<GroupStudent> GroupStudents { get; set; } // GroupStudent.FK_GroupStudent_Student
        /// <summary>
        /// Child Parents where [Parent].[StudentId] point to this entity (FK_Parent_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Parent> Parents { get; set; } // Parent.FK_Parent_Student
        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[StudentId] point to this entity (FK_PhoneNumber_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> PhoneNumbers { get; set; } // PhoneNumber.FK_PhoneNumber_Student
        /// <summary>
        /// Child Registers where [Register].[StudentId] point to this entity (FK_Register_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Register> Registers { get; set; } // Register.FK_Register_Student
        /// <summary>
        /// Child RollCalls where [RollCall].[StudentId] point to this entity (FK_RollCall_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RollCall> RollCalls { get; set; } // RollCall.FK_RollCall_Student
        /// <summary>
        /// Child Scores where [Score].[StudentId] point to this entity (FK_Score_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Score> Scores { get; set; } // Score.FK_Score_Student
        /// <summary>
        /// Child StudentAwards where [StudentAward].[StudentId] point to this entity (FK_StudentAward_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentAward> StudentAwards { get; set; } // StudentAward.FK_StudentAward_Student
        /// <summary>
        /// Child StudentClasses where [StudentClass].[StudentId] point to this entity (FK_StudentClass_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentClass> StudentClasses { get; set; } // StudentClass.FK_StudentClass_Student
        /// <summary>
        /// Child StudentExams where [StudentExam].[StudentId] point to this entity (FK_StudentExam_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentExam> StudentExams { get; set; } // StudentExam.FK_StudentExam_Student
        /// <summary>
        /// Child StudentPersonalities where [StudentPersonality].[StudentId] point to this entity (FK_StudentPersonality_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentPersonality> StudentPersonalities { get; set; } // StudentPersonality.FK_StudentPersonality_Student
        /// <summary>
        /// Child WorkBooks where [WorkBook].[StudentId] point to this entity (FK_WorkBook_Student)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkBook> WorkBooks { get; set; } // WorkBook.FK_WorkBook_Student

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Student].([BasijStatusId]) (FK_Student_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType BasijStatus { get; set; } // FK_Student_GeneralBaseType
        /// <summary>
        /// Parent GeneralBaseType pointed by [Student].([RecordStatusId]) (FK_Student_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_Student_GeneralBaseType1

        public Student()
        {
            ClassPoints = new System.Collections.Generic.List<ClassPoint>();
            ClassScores = new System.Collections.Generic.List<ClassScore>();
            FirstPlace = new System.Collections.Generic.List<Festival>();
            SecondPlace = new System.Collections.Generic.List<Festival>();
            ThirdPlace = new System.Collections.Generic.List<Festival>();
            GroupStudents = new System.Collections.Generic.List<GroupStudent>();
            Parents = new System.Collections.Generic.List<Parent>();
            PhoneNumbers = new System.Collections.Generic.List<PhoneNumber>();
            Registers = new System.Collections.Generic.List<Register>();
            RollCalls = new System.Collections.Generic.List<RollCall>();
            Scores = new System.Collections.Generic.List<Score>();
            StudentAwards = new System.Collections.Generic.List<StudentAward>();
            StudentClasses = new System.Collections.Generic.List<StudentClass>();
            StudentExams = new System.Collections.Generic.List<StudentExam>();
            StudentPersonalities = new System.Collections.Generic.List<StudentPersonality>();
            WorkBooks = new System.Collections.Generic.List<WorkBook>();
        }
    }

}
// </auto-generated>
