// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Tag
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Tag
    {
        public int TagId { get; set; } // TagId (Primary key)
        public string Name { get; set; } // Name (length: 30)

        ///<summary>
        /// نوع آیکون تگ
        ///</summary>
        public int TagTypeId { get; set; } // TagTypeId
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child DocumentTags where [DocumentTag].[TagId] point to this entity (FK_DocumentTag_Tag)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DocumentTag> DocumentTags { get; set; } // DocumentTag.FK_DocumentTag_Tag

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Tag].([RecordStatusId]) (FK_Tag_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_Tag_GeneralBaseType1
        /// <summary>
        /// Parent GeneralBaseType pointed by [Tag].([TagTypeId]) (FK_Tag_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType TagType { get; set; } // FK_Tag_GeneralBaseType

        public Tag()
        {
            DocumentTags = new System.Collections.Generic.List<DocumentTag>();
        }
    }

}
// </auto-generated>
