// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Teacher
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Teacher
    {
        public int TeacherId { get; set; } // TeacherId (Primary key)
        public string FirstName { get; set; } // FirstName (length: 30)
        public string LastName { get; set; } // LastName (length: 50)
        public byte[] Picture { get; set; } // Picture (length: 2147483647)

        ///<summary>
        /// کدملی
        ///</summary>
        public int? NationalCode { get; set; } // NationalCode

        ///<summary>
        /// شماره شناسنامه
        ///</summary>
        public int? IdentifierNo { get; set; } // IdentifierNo
        public string FatherName { get; set; } // FatherName (length: 30)
        public int? BasijStatusId { get; set; } // BasijStatusId
        public string Address { get; set; } // Address (length: 200)
        public int? DegreeId { get; set; } // DegreeId

        ///<summary>
        /// رشته تحصیلی
        ///</summary>
        public string FieldStudy { get; set; } // FieldStudy (length: 50)
        public string Email { get; set; } // Email (length: 50)

        ///<summary>
        /// رزومه
        ///</summary>
        public string Resume { get; set; } // Resume (length: 500)
        public System.DateTime? Birthday { get; set; } // Birthday
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child Classes where [Class].[TeacherId] point to this entity (FK_Class_Teacher)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> Classes { get; set; } // Class.FK_Class_Teacher
        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[TeacherId] point to this entity (FK_PhoneNumber_Teacher)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> PhoneNumbers { get; set; } // PhoneNumber.FK_PhoneNumber_Teacher

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Teacher].([BasijStatusId]) (FK_Teacher_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType BasijStatus { get; set; } // FK_Teacher_GeneralBaseType
        /// <summary>
        /// Parent GeneralBaseType pointed by [Teacher].([DegreeId]) (FK_Teacher_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType Degree { get; set; } // FK_Teacher_GeneralBaseType1
        /// <summary>
        /// Parent GeneralBaseType pointed by [Teacher].([RecordStatusId]) (FK_Teacher_GeneralBaseType2)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_Teacher_GeneralBaseType2

        public Teacher()
        {
            Classes = new System.Collections.Generic.List<Class>();
            PhoneNumbers = new System.Collections.Generic.List<PhoneNumber>();
        }
    }

}
// </auto-generated>
