// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // Term
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Term
    {
        public int TermId { get; set; } // TermId (Primary key)
        public string Name { get; set; } // Name (length: 30)
        public System.DateTime StartDate { get; set; } // StartDate
        public System.DateTime EndDate { get; set; } // EndDate

        ///<summary>
        /// شماره دوره
        ///</summary>
        public int Period { get; set; } // Period
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child AwardConfigs where [AwardConfig].[TermId] point to this entity (FK_AwardConfig_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AwardConfig> AwardConfigs { get; set; } // AwardConfig.FK_AwardConfig_Term
        /// <summary>
        /// Child AwardScores where [AwardScore].[TermId] point to this entity (FK_AwardScore_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AwardScore> AwardScores { get; set; } // AwardScore.FK_AwardScore_Term
        /// <summary>
        /// Child Classes where [Class].[TermId] point to this entity (FK_Class_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> Classes { get; set; } // Class.FK_Class_Term
        /// <summary>
        /// Child Groups where [Group].[TermId] point to this entity (FK_Group_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Group> Groups { get; set; } // Group.FK_Group_Term
        /// <summary>
        /// Child Places where [Place].[TermId] point to this entity (FK_Place_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Place> Places { get; set; } // Place.FK_Place_Term
        /// <summary>
        /// Child RankConfigs where [RankConfig].[TermId] point to this entity (FK_RankConfig_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RankConfig> RankConfigs { get; set; } // RankConfig.FK_RankConfig_Term
        /// <summary>
        /// Child Registers where [Register].[TermId] point to this entity (FK_Register_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Register> Registers { get; set; } // Register.FK_Register_Term
        /// <summary>
        /// Child Scores where [Score].[TermId] point to this entity (FK_Score_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Score> Scores { get; set; } // Score.FK_Score_Term
        /// <summary>
        /// Child StudentAwards where [StudentAward].[TermId] point to this entity (FK_StudentAward_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentAward> StudentAwards { get; set; } // StudentAward.FK_StudentAward_Term
        /// <summary>
        /// Child StudentPersonalities where [StudentPersonality].[TermId] point to this entity (FK_StudentPersonality_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentPersonality> StudentPersonalities { get; set; } // StudentPersonality.FK_StudentPersonality_Term
        /// <summary>
        /// Child TermQuestions where [TermQuestion].[TermId] point to this entity (FK_TermQuestion_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TermQuestion> TermQuestions { get; set; } // TermQuestion.FK_TermQuestion_Term
        /// <summary>
        /// Child WorkBooks where [WorkBook].[TermId] point to this entity (FK_WorkBook_Term)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkBook> WorkBooks { get; set; } // WorkBook.FK_WorkBook_Term

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Term].([RecordStatusId]) (FK_Term_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_Term_GeneralBaseType

        public Term()
        {
            AwardConfigs = new System.Collections.Generic.List<AwardConfig>();
            AwardScores = new System.Collections.Generic.List<AwardScore>();
            Classes = new System.Collections.Generic.List<Class>();
            Groups = new System.Collections.Generic.List<Group>();
            Places = new System.Collections.Generic.List<Place>();
            RankConfigs = new System.Collections.Generic.List<RankConfig>();
            Registers = new System.Collections.Generic.List<Register>();
            Scores = new System.Collections.Generic.List<Score>();
            StudentAwards = new System.Collections.Generic.List<StudentAward>();
            StudentPersonalities = new System.Collections.Generic.List<StudentPersonality>();
            TermQuestions = new System.Collections.Generic.List<TermQuestion>();
            WorkBooks = new System.Collections.Generic.List<WorkBook>();
        }
    }

}
// </auto-generated>
