// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    using Mapping;

    // UserRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class UserRole : Infra.Wpf.Repository.ModelBase<UserRole>
    {
        [Column(@"UserRoleId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int UserRoleId { get { return Get<int>(); } set { Set(value); } } // UserRoleId (Primary key)

        [Required]
        public int UserId { get { return Get<int>(); } set { Set(value); } } // UserId

        [Required]
        public int RoleId { get { return Get<int>(); } set { Set(value); } } // RoleId

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [UserRole].([RoleId]) (FK_UserRole_Role)
        /// </summary>
        public virtual Role Role { get; set; } // FK_UserRole_Role

        /// <summary>
        /// Parent User pointed by [UserRole].([UserId]) (FK_UserRole_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserRole_User

        public UserRole()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
