// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // UserPermission
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class UserPermission
    {
        public int UserPermissionId { get; set; } // UserPermissionId (Primary key)
        public int? UserId { get; set; } // UserId
        public int? PermissionId { get; set; } // PermissionId

        // Foreign keys

        /// <summary>
        /// Parent Permission pointed by [UserPermission].([PermissionId]) (FK_UserPermission_Permission)
        /// </summary>
        public virtual Permission Permission { get; set; } // FK_UserPermission_Permission
        /// <summary>
        /// Parent User pointed by [UserPermission].([UserId]) (FK_UserPermission_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserPermission_User
    }

}
// </auto-generated>
