// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    using Mapping;

    // V_UserRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class VUserRole : Infra.Wpf.Repository.ModelBase<VUserRole>
    {
        [Column(@"UserId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int UserId { get { return Get<int>(); } set { Set(value); } } // UserId (Primary key)

        [Column(@"UserName", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [DataType(DataType.Text)]
        public string UserName { get { return Get<string>(); } set { Set(value); } } // UserName (Primary key) (length: 50)

        [Column(@"RoleId", Order = 3, TypeName = "int")]
        [Required]
        [Key]
        public int RoleId { get { return Get<int>(); } set { Set(value); } } // RoleId (Primary key)

        [Column(@"RoleTitle", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        public string RoleTitle { get { return Get<string>(); } set { Set(value); } } // RoleTitle (Primary key) (length: 50)

        public VUserRole()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
