// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Models
{
    using DataAccess.Mappings;

    // WorkBook
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class WorkBook
    {
        public int WorkBookId { get; set; } // WorkBookId (Primary key)
        public int StudentId { get; set; } // StudentId
        public int TermId { get; set; } // TermId

        ///<summary>
        /// امتیاز رتبه بندی
        ///</summary>
        public int RankScore { get; set; } // RankScore

        ///<summary>
        /// امتیاز جوایز
        ///</summary>
        public int AwardScore { get; set; } // AwardScore

        ///<summary>
        /// امتیاز کل
        ///</summary>
        public int TotalScore { get; set; } // TotalScore
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [WorkBook].([RecordStatusId]) (FK_WorkBook_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_WorkBook_GeneralBaseType
        /// <summary>
        /// Parent Student pointed by [WorkBook].([StudentId]) (FK_WorkBook_Student)
        /// </summary>
        public virtual Student Student { get; set; } // FK_WorkBook_Student
        /// <summary>
        /// Parent Term pointed by [WorkBook].([TermId]) (FK_WorkBook_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_WorkBook_Term

        public WorkBook()
        {
            RankScore = 0;
            AwardScore = 0;
            TotalScore = 0;
        }
    }

}
// </auto-generated>
