// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Mapping
{
    using Models;

    // DebtDemandLabel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class DebtDemandLabelMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DebtDemandLabel>
    {
        public DebtDemandLabelMap()
            : this("dbo")
        {
        }

        public DebtDemandLabelMap(string schema)
        {
            ToTable("DebtDemandLabel", schema);
            Property(x => x.DebtDemandLabelId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.DebtDemandId).HasColumnName(@"DebtDemandId").HasColumnType("int");
            Property(x => x.LabelId).HasColumnName(@"LabelId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.DebtDemand).WithMany(b => b.DebtDemandLabels).HasForeignKey(c => c.DebtDemandId).WillCascadeOnDelete(false); // FK_DebtDemandLabel_DebtDemand
            HasRequired(a => a.Label).WithMany(b => b.DebtDemandLabels).HasForeignKey(c => c.LabelId).WillCascadeOnDelete(false); // FK_DebtDemandLabel_Label
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
