// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // AccountDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AccountDetailMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AccountDetail>
    {
        public AccountDetailMap()
            : this("dbo")
        {
        }

        public AccountDetailMap(string schema)
        {
            ToTable("AccountDetail", schema);
            HasKey(x => x.AccountDetailId);

            Property(x => x.AccountDetailId).HasColumnName(@"AccountDetailId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AccountId).HasColumnName(@"AccountId").HasColumnType("int").IsOptional();
            Property(x => x.BillDate).HasColumnName(@"BillDate").HasColumnType("date").IsOptional();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(150);
            Property(x => x.Count).HasColumnName(@"Count").HasColumnType("int").IsRequired();
            Property(x => x.BaseCharge).HasColumnName(@"BaseCharge").HasColumnType("int").IsRequired();
            Property(x => x.Creditor).HasColumnName(@"Creditor").HasColumnType("int").IsRequired();
            Property(x => x.Debtor).HasColumnName(@"Debtor").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
