// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // Account
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AccountMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Account>
    {
        public AccountMap()
            : this("dbo")
        {
        }

        public AccountMap(string schema)
        {
            ToTable("Account", schema);
            HasKey(x => x.AcountId);

            Property(x => x.AcountId).HasColumnName(@"AcountId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int").IsRequired();
            Property(x => x.BillDate).HasColumnName(@"BillDate").HasColumnType("date").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(150);
            Property(x => x.Count).HasColumnName(@"Count").HasColumnType("int").IsOptional();
            Property(x => x.BaseCharge).HasColumnName(@"BaseCharge").HasColumnType("int").IsOptional();
            Property(x => x.Creditor).HasColumnName(@"Creditor").HasColumnType("int").IsOptional();
            Property(x => x.Debtor).HasColumnName(@"Debtor").HasColumnType("int").IsOptional();
            Property(x => x.IsDetailed).HasColumnName(@"IsDetailed").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
