// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // Award
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AwardMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Award>
    {
        public AwardMap()
            : this("dbo")
        {
        }

        public AwardMap(string schema)
        {
            ToTable("Award", schema);
            HasKey(x => x.AwardId);

            Property(x => x.AwardId).HasColumnName(@"AwardId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.Count).HasColumnName(@"Count").HasColumnType("int").IsOptional();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.Awards).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Award_GeneralBaseType
        }
    }

}
// </auto-generated>
