// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // Camp
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class CampMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Camp>
    {
        public CampMap()
            : this("dbo")
        {
        }

        public CampMap(string schema)
        {
            ToTable("Camp", schema);
            HasKey(x => x.CampId);

            Property(x => x.CampId).HasColumnName(@"CampId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClassSessionId).HasColumnName(@"ClassSessionId").HasColumnType("int").IsRequired();
            Property(x => x.Domestic).HasColumnName(@"Domestic").HasColumnType("bit").IsRequired();
            Property(x => x.PlaceId).HasColumnName(@"PlaceId").HasColumnType("int").IsRequired();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.ClassSession).WithMany(b => b.Camps).HasForeignKey(c => c.ClassSessionId).WillCascadeOnDelete(false); // FK_Camp_ClassSession
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.Camps).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Camp_GeneralBaseType
            HasRequired(a => a.Place).WithMany(b => b.Camps).HasForeignKey(c => c.PlaceId).WillCascadeOnDelete(false); // FK_Camp_Place
        }
    }

}
// </auto-generated>
