// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // DocumentTag
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class DocumentTagMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DocumentTag>
    {
        public DocumentTagMap()
            : this("dbo")
        {
        }

        public DocumentTagMap(string schema)
        {
            ToTable("DocumentTag", schema);
            HasKey(x => x.DocumentTagId);

            Property(x => x.DocumentTagId).HasColumnName(@"DocumentTagId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TagId).HasColumnName(@"TagId").HasColumnType("int").IsRequired();
            Property(x => x.DocumentId).HasColumnName(@"DocumentId").HasColumnType("int").IsRequired();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Document).WithMany(b => b.DocumentTags).HasForeignKey(c => c.DocumentId).WillCascadeOnDelete(false); // FK_DocumentTag_Document
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.DocumentTags).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_DocumentTag_GeneralBaseType
            HasRequired(a => a.Tag).WithMany(b => b.DocumentTags).HasForeignKey(c => c.TagId).WillCascadeOnDelete(false); // FK_DocumentTag_Tag
        }
    }

}
// </auto-generated>
