// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // Exam
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class ExamMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Exam>
    {
        public ExamMap()
            : this("dbo")
        {
        }

        public ExamMap(string schema)
        {
            ToTable("Exam", schema);
            HasKey(x => x.ExamId);

            Property(x => x.ExamId).HasColumnName(@"ExamId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClassId).HasColumnName(@"ClassId").HasColumnType("int").IsRequired();
            Property(x => x.ExamTypeId).HasColumnName(@"ExamTypeId").HasColumnType("int").IsRequired();
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("date").IsOptional();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Class).WithMany(b => b.Exams).HasForeignKey(c => c.ClassId).WillCascadeOnDelete(false); // FK_Exam_Class
            HasRequired(a => a.ExamType).WithMany(b => b.ExamType).HasForeignKey(c => c.ExamTypeId).WillCascadeOnDelete(false); // FK_Exam_GeneralBaseType1
            HasRequired(a => a.RecordStatus).WithMany(b => b.Exams_RecordStatusId).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Exam_GeneralBaseType
        }
    }

}
// </auto-generated>
