// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // GeneralBaseCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class GeneralBaseCategoryMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GeneralBaseCategory>
    {
        public GeneralBaseCategoryMap()
            : this("dbo")
        {
        }

        public GeneralBaseCategoryMap(string schema)
        {
            ToTable("GeneralBaseCategory", schema);
            HasKey(x => x.GeneralBaseCategoryId);

            Property(x => x.GeneralBaseCategoryId).HasColumnName(@"GeneralBaseCategoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
        }
    }

}
// </auto-generated>
