// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // GeneralBaseType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class GeneralBaseTypeMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GeneralBaseType>
    {
        public GeneralBaseTypeMap()
            : this("dbo")
        {
        }

        public GeneralBaseTypeMap(string schema)
        {
            ToTable("GeneralBaseType", schema);
            HasKey(x => x.GeneralBaseTypeId);

            Property(x => x.GeneralBaseTypeId).HasColumnName(@"GeneralBaseTypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GeneralBaseCategoryId).HasColumnName(@"GeneralBaseCategoryId").HasColumnType("int").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.Titile).HasColumnName(@"Titile").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.GeneralBaseCategory).WithMany(b => b.GeneralBaseTypes).HasForeignKey(c => c.GeneralBaseCategoryId).WillCascadeOnDelete(false); // FK_GeneralBaseType_GeneralBaseCategory
        }
    }

}
// </auto-generated>
