// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // RankConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class RankConfigMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RankConfig>
    {
        public RankConfigMap()
            : this("dbo")
        {
        }

        public RankConfigMap(string schema)
        {
            ToTable("RankConfig", schema);
            HasKey(x => x.RankConfigId);

            Property(x => x.RankConfigId).HasColumnName(@"RankConfigId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ScoreItemId).HasColumnName(@"ScoreItemId").HasColumnType("int").IsRequired();
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int").IsRequired();
            Property(x => x.Score).HasColumnName(@"Score").HasColumnType("decimal").IsRequired().HasPrecision(4,2);
            Property(x => x.Delay).HasColumnName(@"Delay").HasColumnType("int").IsOptional();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.RankConfigs).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_RankConfig_GeneralBaseType
            HasRequired(a => a.ScoreItem).WithMany(b => b.RankConfigs).HasForeignKey(c => c.ScoreItemId).WillCascadeOnDelete(false); // FK_RankConfig_ScoreItem
            HasRequired(a => a.Term).WithMany(b => b.RankConfigs).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_RankConfig_Term
        }
    }

}
// </auto-generated>
