// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // RolePermission
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class RolePermissionMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RolePermission>
    {
        public RolePermissionMap()
            : this("dbo")
        {
        }

        public RolePermissionMap(string schema)
        {
            ToTable("RolePermission", schema);
            HasKey(x => x.RolePermissionId);

            Property(x => x.RolePermissionId).HasColumnName(@"RolePermissionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int").IsRequired();
            Property(x => x.PermissionId).HasColumnName(@"PermissionId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Permission).WithMany(b => b.RolePermissions).HasForeignKey(c => c.PermissionId).WillCascadeOnDelete(false); // FK_RolePermission_Permission
            HasRequired(a => a.Role).WithMany(b => b.RolePermissions).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_RolePermission_Role
        }
    }

}
// </auto-generated>
