// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // StudentExam
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class StudentExamMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentExam>
    {
        public StudentExamMap()
            : this("dbo")
        {
        }

        public StudentExamMap(string schema)
        {
            ToTable("StudentExam", schema);
            HasKey(x => x.StudentExamId);

            Property(x => x.StudentExamId).HasColumnName(@"StudentExamId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ExamId).HasColumnName(@"ExamId").HasColumnType("int").IsRequired();
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired();
            Property(x => x.ExamMark).HasColumnName(@"ExamMark").HasColumnType("decimal").IsRequired().HasPrecision(4,2);
            Property(x => x.RecordStautsId).HasColumnName(@"RecordStautsId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Exam).WithMany(b => b.StudentExams).HasForeignKey(c => c.ExamId).WillCascadeOnDelete(false); // FK_StudentExam_Exam
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.StudentExams).HasForeignKey(c => c.RecordStautsId).WillCascadeOnDelete(false); // FK_StudentExam_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.StudentExams).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_StudentExam_Student
        }
    }

}
// </auto-generated>
