// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // StudentClass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class StudentClassMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentClass>
    {
        public StudentClassMap()
            : this("dbo")
        {
        }

        public StudentClassMap(string schema)
        {
            ToTable("StudentClass", schema);
            HasKey(x => x.StudentClassId);

            Property(x => x.StudentClassId).HasColumnName(@"StudentClassId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClassId).HasColumnName(@"ClassId").HasColumnType("int").IsRequired();
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Class).WithMany(b => b.StudentClasses).HasForeignKey(c => c.ClassId).WillCascadeOnDelete(false); // FK_StudentClass_Class
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.StudentClasses).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_StudentClass_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.StudentClasses).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_StudentClass_Student
        }
    }

}
// </auto-generated>
