// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // StudentPersonality
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class StudentPersonalityMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentPersonality>
    {
        public StudentPersonalityMap()
            : this("dbo")
        {
        }

        public StudentPersonalityMap(string schema)
        {
            ToTable("StudentPersonality", schema);
            HasKey(x => x.StudentPersonalityId);

            Property(x => x.StudentPersonalityId).HasColumnName(@"StudentPersonalityId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired();
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int").IsRequired();
            Property(x => x.RegisterDate).HasColumnName(@"RegisterDate").HasColumnType("date").IsRequired();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            Property(x => x.Detail).HasColumnName(@"Detail").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_StudentPersonality_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_StudentPersonality_Student
            HasRequired(a => a.Term).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_StudentPersonality_Term
            HasRequired(a => a.User).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_StudentPersonality_User
        }
    }

}
// </auto-generated>
