// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // Tag
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class TagMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tag>
    {
        public TagMap()
            : this("dbo")
        {
        }

        public TagMap(string schema)
        {
            ToTable("Tag", schema);
            HasKey(x => x.TagId);

            Property(x => x.TagId).HasColumnName(@"TagId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            Property(x => x.TagTypeId).HasColumnName(@"TagTypeId").HasColumnType("int").IsRequired();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.RecordStatus).WithMany(b => b.Tags_RecordStatusId).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Tag_GeneralBaseType1
            HasRequired(a => a.TagType).WithMany(b => b.TagType).HasForeignKey(c => c.TagTypeId).WillCascadeOnDelete(false); // FK_Tag_GeneralBaseType
        }
    }

}
// </auto-generated>
