// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataAccess.Mappings
{
    using DataAccess.Models;

    // WorkBook
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class WorkBookMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkBook>
    {
        public WorkBookMap()
            : this("dbo")
        {
        }

        public WorkBookMap(string schema)
        {
            ToTable("WorkBook", schema);
            HasKey(x => x.WorkBookId);

            Property(x => x.WorkBookId).HasColumnName(@"WorkBookId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired();
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int").IsRequired();
            Property(x => x.RankScore).HasColumnName(@"RankScore").HasColumnType("int").IsRequired();
            Property(x => x.AwardScore).HasColumnName(@"AwardScore").HasColumnType("int").IsRequired();
            Property(x => x.TotalScore).HasColumnName(@"TotalScore").HasColumnType("int").IsRequired();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.WorkBooks).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_WorkBook_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.WorkBooks).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_WorkBook_Student
            HasRequired(a => a.Term).WithMany(b => b.WorkBooks).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_WorkBook_Term
        }
    }

}
// </auto-generated>
