// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // Account
    ///<summary>
    /// جدول حساب
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Account
    {
        [Column(@"AcountId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int AcountId { get; set; } // AcountId (Primary key)

        ///<summary>
        /// دوره
        ///</summary>
        [Required]
        public int TermId { get; set; } // TermId

        ///<summary>
        /// تاریخ صورت حساب
        ///</summary>
        [Required]
        public System.DateTime BillDate { get; set; } // BillDate

        ///<summary>
        /// شرح
        ///</summary>
        [Required]
        [MaxLength(150)]
        [StringLength(150)]
        public string Description { get; set; } // Description (length: 150)

        ///<summary>
        /// تعداد اقلام
        ///</summary>
        public int? Count { get; set; } // Count

        ///<summary>
        /// هزینه پایه
        ///</summary>
        public int? BaseCharge { get; set; } // BaseCharge

        ///<summary>
        /// مبلغ طلبکار
        ///</summary>
        public int? Creditor { get; set; } // Creditor

        ///<summary>
        /// مبلغ بدهکار
        ///</summary>
        public int? Debtor { get; set; } // Debtor

        ///<summary>
        /// جزئیات دارد؟
        ///</summary>
        [Required]
        public bool IsDetailed { get; set; } // IsDetailed

        public Account()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
