// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // Award
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class AwardMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Award>
    {
        public AwardMap()
            : this("dbo")
        {
        }

        public AwardMap(string schema)
        {
            ToTable("Award", schema);
            Property(x => x.AwardId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar");
            Property(x => x.Count).HasColumnName(@"Count").HasColumnType("int").IsOptional();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.Awards).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Award_GeneralBaseType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
