// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // Camp
    ///<summary>
    /// جدول اطلاعات جلسات اردو
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Camp
    {
        [Column(@"CampId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Camp ID")]
        public int CampId { get; set; } // CampId (Primary key)

        ///<summary>
        /// جلسه اردو
        ///</summary>
        [Required]
        [Display(Name = "Class session ID")]
        public int ClassSessionId { get; set; } // ClassSessionId

        ///<summary>
        /// اردو خانوادگی
        ///</summary>
        [Required]
        [Display(Name = "Domestic")]
        public bool Domestic { get; set; } // Domestic

        ///<summary>
        /// مکان اردو
        ///</summary>
        [Required]
        [Display(Name = "Place ID")]
        public int PlaceId { get; set; } // PlaceId

        [Required]
        [Display(Name = "Record status ID")]
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent ClassSession pointed by [Camp].([ClassSessionId]) (FK_Camp_ClassSession)
        /// </summary>
        public virtual ClassSession ClassSession { get; set; } // FK_Camp_ClassSession

        /// <summary>
        /// Parent GeneralBaseType pointed by [Camp].([RecordStatusId]) (FK_Camp_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_Camp_GeneralBaseType

        /// <summary>
        /// Parent Place pointed by [Camp].([PlaceId]) (FK_Camp_Place)
        /// </summary>
        public virtual Place Place { get; set; } // FK_Camp_Place

        public Camp()
        {
            Domestic = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
