// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // ClassScadule
    ///<summary>
    /// جدول برنامه کلاسی
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ClassScadule
    {
        [Column(@"ClassScaduleId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Class scadule ID")]
        public int ClassScaduleId { get; set; } // ClassScaduleId (Primary key)

        [Required]
        [Display(Name = "Class ID")]
        public int ClassId { get; set; } // ClassId

        ///<summary>
        /// هفتگی یا روزانه
        ///</summary>
        [Required]
        [Display(Name = "Scadule type ID")]
        public int ScaduleTypeId { get; set; } // ScaduleTypeId

        [Display(Name = "Date")]
        public System.DateTime? Date { get; set; } // Date

        [Display(Name = "Day ID")]
        public int? DayId { get; set; } // DayId

        [Required]
        [Display(Name = "Start time")]
        public System.TimeSpan StartTime { get; set; } // StartTime

        [Required]
        [Display(Name = "End time")]
        public System.TimeSpan EndTime { get; set; } // EndTime

        [Required]
        [Display(Name = "Record status ID")]
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child ClassSessions where [ClassSession].[ClassScaduleId] point to this entity (FK_ClassSession_ClassScadule)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassSession> ClassSessions { get; set; } // ClassSession.FK_ClassSession_ClassScadule

        // Foreign keys

        /// <summary>
        /// Parent Class pointed by [ClassScadule].([ClassId]) (FK_ClassScadule_Class)
        /// </summary>
        public virtual Class Class { get; set; } // FK_ClassScadule_Class

        /// <summary>
        /// Parent GeneralBaseType pointed by [ClassScadule].([RecordStatusId]) (FK_ClassScadule_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_ClassScadule_GeneralBaseType1

        /// <summary>
        /// Parent GeneralBaseType pointed by [ClassScadule].([ScaduleTypeId]) (FK_ClassScadule_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType ScaduleType { get; set; } // FK_ClassScadule_GeneralBaseType

        public ClassScadule()
        {
            ClassSessions = new System.Collections.Generic.List<ClassSession>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
