// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // ClassSession
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ClassSessionMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClassSession>
    {
        public ClassSessionMap()
            : this("dbo")
        {
        }

        public ClassSessionMap(string schema)
        {
            ToTable("ClassSession", schema);
            Property(x => x.ClassSessionId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.ClassScaduleId).HasColumnName(@"ClassScaduleId").HasColumnType("int").IsOptional();
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("date");
            Property(x => x.StatTime).HasColumnName(@"StatTime").HasColumnType("time");
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("time");
            Property(x => x.Holding).HasColumnName(@"Holding").HasColumnType("bit");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasOptional(a => a.ClassScadule).WithMany(b => b.ClassSessions).HasForeignKey(c => c.ClassScaduleId).WillCascadeOnDelete(false); // FK_ClassSession_ClassScadule
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.ClassSessions).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_ClassSession_GeneralBaseType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
