// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // Exam
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ExamMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Exam>
    {
        public ExamMap()
            : this("dbo")
        {
        }

        public ExamMap(string schema)
        {
            ToTable("Exam", schema);
            Property(x => x.ExamId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.ClassId).HasColumnName(@"ClassId").HasColumnType("int");
            Property(x => x.ExamTypeId).HasColumnName(@"ExamTypeId").HasColumnType("int");
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("date").IsOptional();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Class).WithMany(b => b.Exams).HasForeignKey(c => c.ClassId).WillCascadeOnDelete(false); // FK_Exam_Class
            HasRequired(a => a.ExamType).WithMany(b => b.ExamType).HasForeignKey(c => c.ExamTypeId).WillCascadeOnDelete(false); // FK_Exam_GeneralBaseType1
            HasRequired(a => a.RecordStatus).WithMany(b => b.Exams_RecordStatusId).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Exam_GeneralBaseType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
