// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // GeneralBaseCategory
    ///<summary>
    /// جدول گروه بندی انواع عمومی
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class GeneralBaseCategory
    {
        [Column(@"GeneralBaseCategoryId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "General base category ID")]
        public int GeneralBaseCategoryId { get; set; } // GeneralBaseCategoryId (Primary key)

        ///<summary>
        /// عنوان انگلیسی
        ///</summary>
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 30)

        ///<summary>
        /// عنوان فارسی
        ///</summary>
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child GeneralBaseTypes where [GeneralBaseType].[GeneralBaseCategoryId] point to this entity (FK_GeneralBaseType_GeneralBaseCategory)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<GeneralBaseType> GeneralBaseTypes { get; set; } // GeneralBaseType.FK_GeneralBaseType_GeneralBaseCategory

        public GeneralBaseCategory()
        {
            GeneralBaseTypes = new System.Collections.Generic.List<GeneralBaseType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
