// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // GeneralBaseType
    ///<summary>
    /// جدول انواع عمومی
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class GeneralBaseType
    {
        [Column(@"GeneralBaseTypeId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int GeneralBaseTypeId { get; set; } // GeneralBaseTypeId (Primary key)

        [Required]
        public int GeneralBaseCategoryId { get; set; } // GeneralBaseCategoryId

        ///<summary>
        /// عنوان به انگلیسی
        ///</summary>
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        public string Name { get; set; } // Name (length: 30)

        ///<summary>
        /// عنوان به فارسی
        ///</summary>
        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        public string Titile { get; set; } // Titile (length: 30)

        [Required]
        public int Code { get; set; } // Code

        // Reverse navigation

        /// <summary>
        /// Child Awards where [Award].[RecordStatusId] point to this entity (FK_Award_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Award> Awards { get; set; } // Award.FK_Award_GeneralBaseType
        /// <summary>
        /// Child AwardConfigs where [AwardConfig].[RecordStatusId] point to this entity (FK_AwardConfig_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AwardConfig> AwardConfigs { get; set; } // AwardConfig.FK_AwardConfig_GeneralBaseType
        /// <summary>
        /// Child AwardScores where [AwardScore].[RecordStatusId] point to this entity (FK_AwardScore_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AwardScore> AwardScores { get; set; } // AwardScore.FK_AwardScore_GeneralBaseType
        /// <summary>
        /// Child Camps where [Camp].[RecordStatusId] point to this entity (FK_Camp_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Camp> Camps { get; set; } // Camp.FK_Camp_GeneralBaseType
        /// <summary>
        /// Child Classes where [Class].[ClassModelId] point to this entity (FK_Class_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> ClassModel { get; set; } // Class.FK_Class_GeneralBaseType1
        /// <summary>
        /// Child Classes where [Class].[ClassTypeId] point to this entity (FK_Class_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> ClassType { get; set; } // Class.FK_Class_GeneralBaseType
        /// <summary>
        /// Child Classes where [Class].[RecoredStatusId] point to this entity (FK_Class_GeneralBaseType2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> RecoredStatus { get; set; } // Class.FK_Class_GeneralBaseType2
        /// <summary>
        /// Child ClassPoints where [ClassPoint].[RecordStatusId] point to this entity (FK_ClassPoint_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassPoint> ClassPoints { get; set; } // ClassPoint.FK_ClassPoint_GeneralBaseType
        /// <summary>
        /// Child ClassScadules where [ClassScadule].[RecordStatusId] point to this entity (FK_ClassScadule_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassScadule> ClassScadules_RecordStatusId { get; set; } // ClassScadule.FK_ClassScadule_GeneralBaseType1
        /// <summary>
        /// Child ClassScadules where [ClassScadule].[ScaduleTypeId] point to this entity (FK_ClassScadule_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassScadule> ScaduleType { get; set; } // ClassScadule.FK_ClassScadule_GeneralBaseType
        /// <summary>
        /// Child ClassScores where [ClassScore].[RecordStatusId] point to this entity (FK_ClassScore_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassScore> ClassScores_RecordStatusId { get; set; } // ClassScore.FK_ClassScore_GeneralBaseType1
        /// <summary>
        /// Child ClassScores where [ClassScore].[ScoreTypeId] point to this entity (FK_ClassScore_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassScore> ScoreType { get; set; } // ClassScore.FK_ClassScore_GeneralBaseType
        /// <summary>
        /// Child ClassSessions where [ClassSession].[RecordStatusId] point to this entity (FK_ClassSession_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ClassSession> ClassSessions { get; set; } // ClassSession.FK_ClassSession_GeneralBaseType
        /// <summary>
        /// Child Documents where [Document].[RecordStatusId] point to this entity (FK_Document_GeneralBaseType3)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Document> Documents_RecordStatusId { get; set; } // Document.FK_Document_GeneralBaseType3
        /// <summary>
        /// Child Documents where [Document].[DocumentTypeId] point to this entity (FK_Document_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Document> DocumentType { get; set; } // Document.FK_Document_GeneralBaseType1
        /// <summary>
        /// Child Documents where [Document].[ExtensionTypeId] point to this entity (FK_Document_GeneralBaseType2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Document> ExtensionType { get; set; } // Document.FK_Document_GeneralBaseType2
        /// <summary>
        /// Child Documents where [Document].[RootId] point to this entity (FK_Document_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Document> Root { get; set; } // Document.FK_Document_GeneralBaseType
        /// <summary>
        /// Child DocumentTags where [DocumentTag].[RecordStatusId] point to this entity (FK_DocumentTag_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DocumentTag> DocumentTags { get; set; } // DocumentTag.FK_DocumentTag_GeneralBaseType
        /// <summary>
        /// Child Exams where [Exam].[RecordStatusId] point to this entity (FK_Exam_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Exam> Exams_RecordStatusId { get; set; } // Exam.FK_Exam_GeneralBaseType
        /// <summary>
        /// Child Exams where [Exam].[ExamTypeId] point to this entity (FK_Exam_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Exam> ExamType { get; set; } // Exam.FK_Exam_GeneralBaseType1
        /// <summary>
        /// Child Festivals where [Festival].[RecordStatusId] point to this entity (FK_Festival_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Festival> Festivals { get; set; } // Festival.FK_Festival_GeneralBaseType
        /// <summary>
        /// Child Groups where [Group].[RecordStatusId] point to this entity (FK_Group_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Group> Groups { get; set; } // Group.FK_Group_GeneralBaseType
        /// <summary>
        /// Child GroupStudents where [GroupStudent].[RecordStatusId] point to this entity (FK_GroupStudent_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<GroupStudent> GroupStudents { get; set; } // GroupStudent.FK_GroupStudent_GeneralBaseType
        /// <summary>
        /// Child Parents where [Parent].[RecordStatusId] point to this entity (FK_Parent_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Parent> Parents_RecordStatusId { get; set; } // Parent.FK_Parent_GeneralBaseType1
        /// <summary>
        /// Child Parents where [Parent].[RelationshipId] point to this entity (FK_Parent_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Parent> Relationship { get; set; } // Parent.FK_Parent_GeneralBaseType
        /// <summary>
        /// Child Permissions where [Permission].[PermitionTypeId] point to this entity (FK_Permission_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Permission> Permissions { get; set; } // Permission.FK_Permission_GeneralBaseType
        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[OwnerId] point to this entity (FK_PhoneNumber_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> Owner { get; set; } // PhoneNumber.FK_PhoneNumber_GeneralBaseType
        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[RecordStatusId] point to this entity (FK_PhoneNumber_GeneralBaseType2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> PhoneNumbers_RecordStatusId { get; set; } // PhoneNumber.FK_PhoneNumber_GeneralBaseType2
        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[PhoneNumberTypeId] point to this entity (FK_PhoneNumber_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> PhoneNumberType { get; set; } // PhoneNumber.FK_PhoneNumber_GeneralBaseType1
        /// <summary>
        /// Child Places where [Place].[PlaceGroupId] point to this entity (FK_Place_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Place> PlaceGroup { get; set; } // Place.FK_Place_GeneralBaseType1
        /// <summary>
        /// Child Places where [Place].[RecordStatusId] point to this entity (FK_Place_GeneralBaseType2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Place> Places_RecordStatusId { get; set; } // Place.FK_Place_GeneralBaseType2
        /// <summary>
        /// Child Places where [Place].[PlaceTypeId] point to this entity (FK_Place_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Place> PlaceType { get; set; } // Place.FK_Place_GeneralBaseType
        /// <summary>
        /// Child Questions where [Question].[RecordStatusId] point to this entity (FK_Question_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Question> Questions { get; set; } // Question.FK_Question_GeneralBaseType
        /// <summary>
        /// Child QuestionItems where [QuestionItem].[AnswerTypeId] point to this entity (FK_QuestionItem_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<QuestionItem> AnswerType { get; set; } // QuestionItem.FK_QuestionItem_GeneralBaseType1
        /// <summary>
        /// Child QuestionItems where [QuestionItem].[RecordStatusId] point to this entity (FK_QuestionItem_GeneralBaseType2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<QuestionItem> QuestionItems_RecordStatusId { get; set; } // QuestionItem.FK_QuestionItem_GeneralBaseType2
        /// <summary>
        /// Child QuestionItems where [QuestionItem].[QuestionTypeId] point to this entity (FK_QuestionItem_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<QuestionItem> QuestionType { get; set; } // QuestionItem.FK_QuestionItem_GeneralBaseType
        /// <summary>
        /// Child RankConfigs where [RankConfig].[RecordStatusId] point to this entity (FK_RankConfig_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RankConfig> RankConfigs { get; set; } // RankConfig.FK_RankConfig_GeneralBaseType
        /// <summary>
        /// Child Registers where [Register].[AverageTypeId] point to this entity (FK_Register_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Register> AverageType { get; set; } // Register.FK_Register_GeneralBaseType
        /// <summary>
        /// Child Registers where [Register].[RecordStatusId] point to this entity (FK_Register_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Register> Registers_RecordStatusId { get; set; } // Register.FK_Register_GeneralBaseType1
        /// <summary>
        /// Child RegisterQuestions where [RegisterQuestion].[RecordStatusId] point to this entity (FK_RegisterQuestion_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RegisterQuestion> RegisterQuestions { get; set; } // RegisterQuestion.FK_RegisterQuestion_GeneralBaseType
        /// <summary>
        /// Child ReligiousMissions where [ReligiousMission].[RecordStatusId] point to this entity (FK_ReligiousMission_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ReligiousMission> ReligiousMissions { get; set; } // ReligiousMission.FK_ReligiousMission_GeneralBaseType
        /// <summary>
        /// Child Roles where [Role].[RecordStatusId] point to this entity (FK_Role_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Role> Roles { get; set; } // Role.FK_Role_GeneralBaseType
        /// <summary>
        /// Child RollCalls where [RollCall].[PresenceId] point to this entity (FK_RollCall_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RollCall> Presence { get; set; } // RollCall.FK_RollCall_GeneralBaseType
        /// <summary>
        /// Child RollCalls where [RollCall].[RecordStatusId] point to this entity (FK_RollCall_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RollCall> RollCalls_RecordStatusId { get; set; } // RollCall.FK_RollCall_GeneralBaseType1
        /// <summary>
        /// Child Scores where [Score].[RecordStatusId] point to this entity (FK_Score_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Score> Scores { get; set; } // Score.FK_Score_GeneralBaseType
        /// <summary>
        /// Child Students where [Student].[BasijStatusId] point to this entity (FK_Student_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Student> BasijStatus { get; set; } // Student.FK_Student_GeneralBaseType
        /// <summary>
        /// Child Students where [Student].[RecordStatusId] point to this entity (FK_Student_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Student> Students_RecordStatusId { get; set; } // Student.FK_Student_GeneralBaseType1
        /// <summary>
        /// Child StudentAwards where [StudentAward].[RecordStatusId] point to this entity (FK_StudentAward_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentAward> StudentAwards { get; set; } // StudentAward.FK_StudentAward_GeneralBaseType
        /// <summary>
        /// Child StudentClasses where [StudentClass].[RecordStatusId] point to this entity (FK_StudentClass_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentClass> StudentClasses { get; set; } // StudentClass.FK_StudentClass_GeneralBaseType
        /// <summary>
        /// Child StudentExams where [StudentExam].[RecordStautsId] point to this entity (FK_StudentExam_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentExam> StudentExams { get; set; } // StudentExam.FK_StudentExam_GeneralBaseType
        /// <summary>
        /// Child StudentPersonalities where [StudentPersonality].[RecordStatusId] point to this entity (FK_StudentPersonality_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<StudentPersonality> StudentPersonalities { get; set; } // StudentPersonality.FK_StudentPersonality_GeneralBaseType
        /// <summary>
        /// Child Tags where [Tag].[RecordStatusId] point to this entity (FK_Tag_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Tag> Tags_RecordStatusId { get; set; } // Tag.FK_Tag_GeneralBaseType1
        /// <summary>
        /// Child Tags where [Tag].[TagTypeId] point to this entity (FK_Tag_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Tag> TagType { get; set; } // Tag.FK_Tag_GeneralBaseType
        /// <summary>
        /// Child Teachers where [Teacher].[BasijStatusId] point to this entity (FK_Teacher_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Teacher> BasijStatusId { get; set; } // Teacher.FK_Teacher_GeneralBaseType
        /// <summary>
        /// Child Teachers where [Teacher].[DegreeId] point to this entity (FK_Teacher_GeneralBaseType1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Teacher> Degree { get; set; } // Teacher.FK_Teacher_GeneralBaseType1
        /// <summary>
        /// Child Teachers where [Teacher].[RecordStatusId] point to this entity (FK_Teacher_GeneralBaseType2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Teacher> Teachers_RecordStatusId { get; set; } // Teacher.FK_Teacher_GeneralBaseType2
        /// <summary>
        /// Child Terms where [Term].[RecordStatusId] point to this entity (FK_Term_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Term> Terms { get; set; } // Term.FK_Term_GeneralBaseType
        /// <summary>
        /// Child Users where [User].[RecordStatusId] point to this entity (FK_User_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<User> Users { get; set; } // User.FK_User_GeneralBaseType
        /// <summary>
        /// Child WorkBooks where [WorkBook].[RecordStatusId] point to this entity (FK_WorkBook_GeneralBaseType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<WorkBook> WorkBooks { get; set; } // WorkBook.FK_WorkBook_GeneralBaseType

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseCategory pointed by [GeneralBaseType].([GeneralBaseCategoryId]) (FK_GeneralBaseType_GeneralBaseCategory)
        /// </summary>
        public virtual GeneralBaseCategory GeneralBaseCategory { get; set; } // FK_GeneralBaseType_GeneralBaseCategory

        public GeneralBaseType()
        {
            Awards = new System.Collections.Generic.List<Award>();
            AwardConfigs = new System.Collections.Generic.List<AwardConfig>();
            AwardScores = new System.Collections.Generic.List<AwardScore>();
            Camps = new System.Collections.Generic.List<Camp>();
            ClassModel = new System.Collections.Generic.List<Class>();
            ClassType = new System.Collections.Generic.List<Class>();
            RecoredStatus = new System.Collections.Generic.List<Class>();
            ClassPoints = new System.Collections.Generic.List<ClassPoint>();
            ClassScadules_RecordStatusId = new System.Collections.Generic.List<ClassScadule>();
            ScaduleType = new System.Collections.Generic.List<ClassScadule>();
            ClassScores_RecordStatusId = new System.Collections.Generic.List<ClassScore>();
            ScoreType = new System.Collections.Generic.List<ClassScore>();
            ClassSessions = new System.Collections.Generic.List<ClassSession>();
            DocumentType = new System.Collections.Generic.List<Document>();
            ExtensionType = new System.Collections.Generic.List<Document>();
            Documents_RecordStatusId = new System.Collections.Generic.List<Document>();
            Root = new System.Collections.Generic.List<Document>();
            DocumentTags = new System.Collections.Generic.List<DocumentTag>();
            ExamType = new System.Collections.Generic.List<Exam>();
            Exams_RecordStatusId = new System.Collections.Generic.List<Exam>();
            Festivals = new System.Collections.Generic.List<Festival>();
            Groups = new System.Collections.Generic.List<Group>();
            GroupStudents = new System.Collections.Generic.List<GroupStudent>();
            Parents_RecordStatusId = new System.Collections.Generic.List<Parent>();
            Relationship = new System.Collections.Generic.List<Parent>();
            Permissions = new System.Collections.Generic.List<Permission>();
            Owner = new System.Collections.Generic.List<PhoneNumber>();
            PhoneNumberType = new System.Collections.Generic.List<PhoneNumber>();
            PhoneNumbers_RecordStatusId = new System.Collections.Generic.List<PhoneNumber>();
            PlaceGroup = new System.Collections.Generic.List<Place>();
            PlaceType = new System.Collections.Generic.List<Place>();
            Places_RecordStatusId = new System.Collections.Generic.List<Place>();
            Questions = new System.Collections.Generic.List<Question>();
            AnswerType = new System.Collections.Generic.List<QuestionItem>();
            QuestionType = new System.Collections.Generic.List<QuestionItem>();
            QuestionItems_RecordStatusId = new System.Collections.Generic.List<QuestionItem>();
            RankConfigs = new System.Collections.Generic.List<RankConfig>();
            AverageType = new System.Collections.Generic.List<Register>();
            Registers_RecordStatusId = new System.Collections.Generic.List<Register>();
            RegisterQuestions = new System.Collections.Generic.List<RegisterQuestion>();
            ReligiousMissions = new System.Collections.Generic.List<ReligiousMission>();
            Roles = new System.Collections.Generic.List<Role>();
            Presence = new System.Collections.Generic.List<RollCall>();
            RollCalls_RecordStatusId = new System.Collections.Generic.List<RollCall>();
            Scores = new System.Collections.Generic.List<Score>();
            BasijStatus = new System.Collections.Generic.List<Student>();
            Students_RecordStatusId = new System.Collections.Generic.List<Student>();
            StudentAwards = new System.Collections.Generic.List<StudentAward>();
            StudentClasses = new System.Collections.Generic.List<StudentClass>();
            StudentExams = new System.Collections.Generic.List<StudentExam>();
            StudentPersonalities = new System.Collections.Generic.List<StudentPersonality>();
            Tags_RecordStatusId = new System.Collections.Generic.List<Tag>();
            TagType = new System.Collections.Generic.List<Tag>();
            BasijStatusId = new System.Collections.Generic.List<Teacher>();
            Degree = new System.Collections.Generic.List<Teacher>();
            Teachers_RecordStatusId = new System.Collections.Generic.List<Teacher>();
            Terms = new System.Collections.Generic.List<Term>();
            Users = new System.Collections.Generic.List<User>();
            WorkBooks = new System.Collections.Generic.List<WorkBook>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
