// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // GroupStudent
    ///<summary>
    /// جدول دانش آموزان گروه
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class GroupStudent
    {
        [Column(@"GroupStudentId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int GroupStudentId { get; set; } // GroupStudentId (Primary key)

        [Required]
        public int GroupId { get; set; } // GroupId

        [Required]
        public int StudentId { get; set; } // StudentId

        [Required]
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [GroupStudent].([RecordStatusId]) (FK_GroupStudent_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_GroupStudent_GeneralBaseType

        /// <summary>
        /// Parent Group pointed by [GroupStudent].([GroupId]) (FK_GroupStudent_GroupStudent)
        /// </summary>
        public virtual Group Group { get; set; } // FK_GroupStudent_GroupStudent

        /// <summary>
        /// Parent Student pointed by [GroupStudent].([StudentId]) (FK_GroupStudent_Student)
        /// </summary>
        public virtual Student Student { get; set; } // FK_GroupStudent_Student

        public GroupStudent()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
