// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // GroupStudent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class GroupStudentMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GroupStudent>
    {
        public GroupStudentMap()
            : this("dbo")
        {
        }

        public GroupStudentMap(string schema)
        {
            ToTable("GroupStudent", schema);
            Property(x => x.GroupStudentId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.GroupId).HasColumnName(@"GroupId").HasColumnType("int");
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.GroupStudents).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_GroupStudent_GeneralBaseType
            HasRequired(a => a.Group).WithMany(b => b.GroupStudents).HasForeignKey(c => c.GroupId).WillCascadeOnDelete(false); // FK_GroupStudent_GroupStudent
            HasRequired(a => a.Student).WithMany(b => b.GroupStudents).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_GroupStudent_Student
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
