// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // Group
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class GroupMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Group>
    {
        public GroupMap()
            : this("dbo")
        {
        }

        public GroupMap(string schema)
        {
            ToTable("Group", schema);
            Property(x => x.GroupId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int");
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.Groups).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Group_GeneralBaseType
            HasRequired(a => a.Term).WithMany(b => b.Groups).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_Group_Term
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
