// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    public interface IMyDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Account> Accounts { get; set; } // Account
        System.Data.Entity.DbSet<AccountDetail> AccountDetails { get; set; } // AccountDetail
        System.Data.Entity.DbSet<Award> Awards { get; set; } // Award
        System.Data.Entity.DbSet<AwardConfig> AwardConfigs { get; set; } // AwardConfig
        System.Data.Entity.DbSet<AwardScore> AwardScores { get; set; } // AwardScore
        System.Data.Entity.DbSet<Camp> Camps { get; set; } // Camp
        System.Data.Entity.DbSet<Class> Classes { get; set; } // Class
        System.Data.Entity.DbSet<ClassPoint> ClassPoints { get; set; } // ClassPoint
        System.Data.Entity.DbSet<ClassScadule> ClassScadules { get; set; } // ClassScadule
        System.Data.Entity.DbSet<ClassScore> ClassScores { get; set; } // ClassScore
        System.Data.Entity.DbSet<ClassSession> ClassSessions { get; set; } // ClassSession
        System.Data.Entity.DbSet<Document> Documents { get; set; } // Document
        System.Data.Entity.DbSet<DocumentTag> DocumentTags { get; set; } // DocumentTag
        System.Data.Entity.DbSet<Exam> Exams { get; set; } // Exam
        System.Data.Entity.DbSet<Festival> Festivals { get; set; } // Festival
        System.Data.Entity.DbSet<GeneralBaseCategory> GeneralBaseCategories { get; set; } // GeneralBaseCategory
        System.Data.Entity.DbSet<GeneralBaseType> GeneralBaseTypes { get; set; } // GeneralBaseType
        System.Data.Entity.DbSet<Group> Groups { get; set; } // Group
        System.Data.Entity.DbSet<GroupStudent> GroupStudents { get; set; } // GroupStudent
        System.Data.Entity.DbSet<Parent> Parents { get; set; } // Parent
        System.Data.Entity.DbSet<Permission> Permissions { get; set; } // Permission
        System.Data.Entity.DbSet<PhoneNumber> PhoneNumbers { get; set; } // PhoneNumber
        System.Data.Entity.DbSet<Place> Places { get; set; } // Place
        System.Data.Entity.DbSet<Question> Questions { get; set; } // Question
        System.Data.Entity.DbSet<QuestionItem> QuestionItems { get; set; } // QuestionItem
        System.Data.Entity.DbSet<RankConfig> RankConfigs { get; set; } // RankConfig
        System.Data.Entity.DbSet<Register> Registers { get; set; } // Register
        System.Data.Entity.DbSet<RegisterQuestion> RegisterQuestions { get; set; } // RegisterQuestion
        System.Data.Entity.DbSet<ReligiousMission> ReligiousMissions { get; set; } // ReligiousMission
        System.Data.Entity.DbSet<Role> Roles { get; set; } // Role
        System.Data.Entity.DbSet<RolePermission> RolePermissions { get; set; } // RolePermission
        System.Data.Entity.DbSet<RollCall> RollCalls { get; set; } // RollCall
        System.Data.Entity.DbSet<Score> Scores { get; set; } // Score
        System.Data.Entity.DbSet<ScoreItem> ScoreItems { get; set; } // ScoreItem
        System.Data.Entity.DbSet<Student> Students { get; set; } // Student
        System.Data.Entity.DbSet<StudentAward> StudentAwards { get; set; } // StudentAward
        System.Data.Entity.DbSet<StudentClass> StudentClasses { get; set; } // StudentClass
        System.Data.Entity.DbSet<StudentExam> StudentExams { get; set; } // StudentExam
        System.Data.Entity.DbSet<StudentPersonality> StudentPersonalities { get; set; } // StudentPersonality
        System.Data.Entity.DbSet<Tag> Tags { get; set; } // Tag
        System.Data.Entity.DbSet<Teacher> Teachers { get; set; } // Teacher
        System.Data.Entity.DbSet<Term> Terms { get; set; } // Term
        System.Data.Entity.DbSet<TermQuestion> TermQuestions { get; set; } // TermQuestion
        System.Data.Entity.DbSet<User> Users { get; set; } // User
        System.Data.Entity.DbSet<UserPermission> UserPermissions { get; set; } // UserPermission
        System.Data.Entity.DbSet<WorkBook> WorkBooks { get; set; } // WorkBook

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
