// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // RankConfig
    ///<summary>
    /// جدول تنظیمات امتیازات رتبه ای
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class RankConfig
    {
        [Column(@"RankConfigId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Rank config ID")]
        public int RankConfigId { get; set; } // RankConfigId (Primary key)

        ///<summary>
        /// عنوان امتیاز
        ///</summary>
        [Required]
        [Display(Name = "Score item ID")]
        public int ScoreItemId { get; set; } // ScoreItemId

        [Required]
        [Display(Name = "Term ID")]
        public int TermId { get; set; } // TermId

        [Required]
        [Display(Name = "Score")]
        public decimal Score { get; set; } // Score

        ///<summary>
        /// میزان تاخیر
        ///</summary>
        [Display(Name = "Delay")]
        public int? Delay { get; set; } // Delay

        [Required]
        [Display(Name = "Record status ID")]
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [RankConfig].([RecordStatusId]) (FK_RankConfig_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_RankConfig_GeneralBaseType

        /// <summary>
        /// Parent ScoreItem pointed by [RankConfig].([ScoreItemId]) (FK_RankConfig_ScoreItem)
        /// </summary>
        public virtual ScoreItem ScoreItem { get; set; } // FK_RankConfig_ScoreItem

        /// <summary>
        /// Parent Term pointed by [RankConfig].([TermId]) (FK_RankConfig_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_RankConfig_Term

        public RankConfig()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
