// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // ReligiousMission
    ///<summary>
    /// جدول مشخصات جلسات هیئت
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ReligiousMission
    {
        [Column(@"ReligiousMissionId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int ReligiousMissionId { get; set; } // ReligiousMissionId (Primary key)

        ///<summary>
        /// جلسه هئیت
        ///</summary>
        [Required]
        public int ClassSessionId { get; set; } // ClassSessionId

        ///<summary>
        /// هیئت خانوادگی
        ///</summary>
        [Required]
        public bool Domestic { get; set; } // Domestic

        ///<summary>
        /// مکان هیئت
        ///</summary>
        [Required]
        public int PlaceId { get; set; } // PlaceId

        [Required]
        public int RecordStatusId { get; set; } // RecordStatusId

        // Foreign keys

        /// <summary>
        /// Parent ClassSession pointed by [ReligiousMission].([ClassSessionId]) (FK_ReligiousMission_ClassSession)
        /// </summary>
        public virtual ClassSession ClassSession { get; set; } // FK_ReligiousMission_ClassSession

        /// <summary>
        /// Parent GeneralBaseType pointed by [ReligiousMission].([RecordStatusId]) (FK_ReligiousMission_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_ReligiousMission_GeneralBaseType

        /// <summary>
        /// Parent Place pointed by [ReligiousMission].([PlaceId]) (FK_ReligiousMission_Place)
        /// </summary>
        public virtual Place Place { get; set; } // FK_ReligiousMission_Place

        public ReligiousMission()
        {
            Domestic = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
