// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // ScoreItem
    ///<summary>
    /// جدول گزینه های امتیازدهی
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ScoreItem
    {
        [Column(@"ScoreItemId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Score item ID")]
        public int ScoreItemId { get; set; } // ScoreItemId (Primary key)

        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 30)

        [Required]
        [Display(Name = "Code")]
        public int Code { get; set; } // Code

        // Reverse navigation

        /// <summary>
        /// Child AwardConfigs where [AwardConfig].[ScoreItemId] point to this entity (FK_AwardConfig_ScoreItem)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AwardConfig> AwardConfigs { get; set; } // AwardConfig.FK_AwardConfig_ScoreItem
        /// <summary>
        /// Child RankConfigs where [RankConfig].[ScoreItemId] point to this entity (FK_RankConfig_ScoreItem)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RankConfig> RankConfigs { get; set; } // RankConfig.FK_RankConfig_ScoreItem
        /// <summary>
        /// Child Scores where [Score].[ScoreItemId] point to this entity (FK_Score_ScoreItem)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Score> Scores { get; set; } // Score.FK_Score_ScoreItem

        public ScoreItem()
        {
            AwardConfigs = new System.Collections.Generic.List<AwardConfig>();
            RankConfigs = new System.Collections.Generic.List<RankConfig>();
            Scores = new System.Collections.Generic.List<Score>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
