// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // StudentExam
    ///<summary>
    /// جدول نمرات امتحان دانش آموز
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class StudentExam
    {
        [Column(@"StudentExamId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int StudentExamId { get; set; } // StudentExamId (Primary key)

        [Required]
        public int ExamId { get; set; } // ExamId

        [Required]
        public int StudentId { get; set; } // StudentId

        [Required]
        public decimal ExamMark { get; set; } // ExamMark

        [Required]
        public int RecordStautsId { get; set; } // RecordStautsId

        // Foreign keys

        /// <summary>
        /// Parent Exam pointed by [StudentExam].([ExamId]) (FK_StudentExam_Exam)
        /// </summary>
        public virtual Exam Exam { get; set; } // FK_StudentExam_Exam

        /// <summary>
        /// Parent GeneralBaseType pointed by [StudentExam].([RecordStautsId]) (FK_StudentExam_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType GeneralBaseType { get; set; } // FK_StudentExam_GeneralBaseType

        /// <summary>
        /// Parent Student pointed by [StudentExam].([StudentId]) (FK_StudentExam_Student)
        /// </summary>
        public virtual Student Student { get; set; } // FK_StudentExam_Student

        public StudentExam()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
