// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // StudentAward
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class StudentAwardMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentAward>
    {
        public StudentAwardMap()
            : this("dbo")
        {
        }

        public StudentAwardMap(string schema)
        {
            ToTable("StudentAward", schema);
            Property(x => x.StudentAwardId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int");
            Property(x => x.AwardId).HasColumnName(@"AwardId").HasColumnType("int");
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int");
            Property(x => x.AwardScoreId).HasColumnName(@"AwardScoreId").HasColumnType("int");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Award).WithMany(b => b.StudentAwards).HasForeignKey(c => c.AwardId).WillCascadeOnDelete(false); // FK_StudentAward_Award
            HasRequired(a => a.AwardScore).WithMany(b => b.StudentAwards).HasForeignKey(c => c.AwardScoreId).WillCascadeOnDelete(false); // FK_StudentAward_AwardScore
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.StudentAwards).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_StudentAward_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.StudentAwards).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_StudentAward_Student
            HasRequired(a => a.Term).WithMany(b => b.StudentAwards).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_StudentAward_Term
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
