// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // StudentPersonality
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class StudentPersonalityMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentPersonality>
    {
        public StudentPersonalityMap()
            : this("dbo")
        {
        }

        public StudentPersonalityMap(string schema)
        {
            ToTable("StudentPersonality", schema);
            Property(x => x.StudentPersonalityId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int");
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int");
            Property(x => x.RegisterDate).HasColumnName(@"RegisterDate").HasColumnType("date");
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int");
            Property(x => x.Detail).HasColumnName(@"Detail").HasColumnType("nvarchar");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_StudentPersonality_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_StudentPersonality_Student
            HasRequired(a => a.Term).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_StudentPersonality_Term
            HasRequired(a => a.User).WithMany(b => b.StudentPersonalities).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_StudentPersonality_User
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
