// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // StudentClass
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class StudentClassMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentClass>
    {
        public StudentClassMap()
            : this("dbo")
        {
        }

        public StudentClassMap(string schema)
        {
            ToTable("StudentClass", schema);
            Property(x => x.StudentClassId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.ClassId).HasColumnName(@"ClassId").HasColumnType("int");
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Class).WithMany(b => b.StudentClasses).HasForeignKey(c => c.ClassId).WillCascadeOnDelete(false); // FK_StudentClass_Class
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.StudentClasses).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_StudentClass_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.StudentClasses).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_StudentClass_Student
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
