// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // Teacher
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class TeacherMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Teacher>
    {
        public TeacherMap()
            : this("dbo")
        {
        }

        public TeacherMap(string schema)
        {
            ToTable("Teacher", schema);
            Property(x => x.TeacherId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar");
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar");
            Property(x => x.Picture).HasColumnName(@"Picture").HasColumnType("image").IsOptional();
            Property(x => x.NationalCode).HasColumnName(@"NationalCode").HasColumnType("int").IsOptional();
            Property(x => x.IdentifierNo).HasColumnName(@"IdentifierNo").HasColumnType("int").IsOptional();
            Property(x => x.FatherName).HasColumnName(@"FatherName").HasColumnType("nvarchar").IsOptional();
            Property(x => x.BasijStatusId).HasColumnName(@"BasijStatusId").HasColumnType("int").IsOptional();
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsOptional();
            Property(x => x.DegreeId).HasColumnName(@"DegreeId").HasColumnType("int").IsOptional();
            Property(x => x.FieldStudy).HasColumnName(@"FieldStudy").HasColumnType("nvarchar").IsOptional();
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsOptional();
            Property(x => x.Resume).HasColumnName(@"Resume").HasColumnType("nvarchar").IsOptional();
            Property(x => x.Birthday).HasColumnName(@"Birthday").HasColumnType("date").IsOptional();
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasOptional(a => a.BasijStatus).WithMany(b => b.BasijStatusId).HasForeignKey(c => c.BasijStatusId).WillCascadeOnDelete(false); // FK_Teacher_GeneralBaseType
            HasOptional(a => a.Degree).WithMany(b => b.Degree).HasForeignKey(c => c.DegreeId).WillCascadeOnDelete(false); // FK_Teacher_GeneralBaseType1
            HasRequired(a => a.RecordStatus).WithMany(b => b.Teachers_RecordStatusId).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_Teacher_GeneralBaseType2
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
