// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // Teacher
    ///<summary>
    /// جدول معلمان
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Teacher
    {
        [Column(@"TeacherId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Teacher ID")]
        public int TeacherId { get; set; } // TeacherId (Primary key)

        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "First name")]
        public string FirstName { get; set; } // FirstName (length: 30)

        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Last name")]
        public string LastName { get; set; } // LastName (length: 50)

        [MaxLength(2147483647)]
        [Display(Name = "Picture")]
        public byte[] Picture { get; set; } // Picture (length: 2147483647)

        ///<summary>
        /// کدملی
        ///</summary>
        [Display(Name = "National code")]
        public int? NationalCode { get; set; } // NationalCode

        ///<summary>
        /// شماره شناسنامه
        ///</summary>
        [Display(Name = "Identifier no")]
        public int? IdentifierNo { get; set; } // IdentifierNo

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Father name")]
        public string FatherName { get; set; } // FatherName (length: 30)

        [Display(Name = "Basij status ID")]
        public int? BasijStatusId { get; set; } // BasijStatusId

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Address")]
        public string Address { get; set; } // Address (length: 200)

        [Display(Name = "Degree ID")]
        public int? DegreeId { get; set; } // DegreeId

        ///<summary>
        /// رشته تحصیلی
        ///</summary>
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Field study")]
        public string FieldStudy { get; set; } // FieldStudy (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 50)

        ///<summary>
        /// رزومه
        ///</summary>
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Resume")]
        public string Resume { get; set; } // Resume (length: 500)

        [Display(Name = "Birthday")]
        public System.DateTime? Birthday { get; set; } // Birthday

        [Required]
        [Display(Name = "Record status ID")]
        public int RecordStatusId { get; set; } // RecordStatusId

        // Reverse navigation

        /// <summary>
        /// Child Classes where [Class].[TeacherId] point to this entity (FK_Class_Teacher)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Class> Classes { get; set; } // Class.FK_Class_Teacher
        /// <summary>
        /// Child PhoneNumbers where [PhoneNumber].[TeacherId] point to this entity (FK_PhoneNumber_Teacher)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PhoneNumber> PhoneNumbers { get; set; } // PhoneNumber.FK_PhoneNumber_Teacher

        // Foreign keys

        /// <summary>
        /// Parent GeneralBaseType pointed by [Teacher].([BasijStatusId]) (FK_Teacher_GeneralBaseType)
        /// </summary>
        public virtual GeneralBaseType BasijStatus { get; set; } // FK_Teacher_GeneralBaseType

        /// <summary>
        /// Parent GeneralBaseType pointed by [Teacher].([DegreeId]) (FK_Teacher_GeneralBaseType1)
        /// </summary>
        public virtual GeneralBaseType Degree { get; set; } // FK_Teacher_GeneralBaseType1

        /// <summary>
        /// Parent GeneralBaseType pointed by [Teacher].([RecordStatusId]) (FK_Teacher_GeneralBaseType2)
        /// </summary>
        public virtual GeneralBaseType RecordStatus { get; set; } // FK_Teacher_GeneralBaseType2

        public Teacher()
        {
            Classes = new System.Collections.Generic.List<Class>();
            PhoneNumbers = new System.Collections.Generic.List<PhoneNumber>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
