// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess
{

    // TermQuestion
    ///<summary>
    /// جدول سوالات دوره
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class TermQuestion
    {
        [Column(@"TermQuestionId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        public int TermQuestionId { get; set; } // TermQuestionId (Primary key)

        [Required]
        public int TermId { get; set; } // TermId

        [Required]
        public int QuestionId { get; set; } // QuestionId

        // Reverse navigation

        /// <summary>
        /// Child RegisterQuestions where [RegisterQuestion].[TermQuestionId] point to this entity (FK_RegisterQuestion_TermQuestion)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RegisterQuestion> RegisterQuestions { get; set; } // RegisterQuestion.FK_RegisterQuestion_TermQuestion

        // Foreign keys

        /// <summary>
        /// Parent Question pointed by [TermQuestion].([QuestionId]) (FK_TermQuestion_Question)
        /// </summary>
        public virtual Question Question { get; set; } // FK_TermQuestion_Question

        /// <summary>
        /// Parent Term pointed by [TermQuestion].([TermId]) (FK_TermQuestion_Term)
        /// </summary>
        public virtual Term Term { get; set; } // FK_TermQuestion_Term

        public TermQuestion()
        {
            RegisterQuestions = new System.Collections.Generic.List<RegisterQuestion>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
