// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // TermQuestion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class TermQuestionMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TermQuestion>
    {
        public TermQuestionMap()
            : this("dbo")
        {
        }

        public TermQuestionMap(string schema)
        {
            ToTable("TermQuestion", schema);
            Property(x => x.TermQuestionId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int");
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Question).WithMany(b => b.TermQuestions).HasForeignKey(c => c.QuestionId).WillCascadeOnDelete(false); // FK_TermQuestion_Question
            HasRequired(a => a.Term).WithMany(b => b.TermQuestions).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_TermQuestion_Term
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
