// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // UserPermission
    ///<summary>
    /// جدول سطح دسترسی کاربر
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class UserPermission
    {
        [Column(@"UserPermissionId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "User permission ID")]
        public int UserPermissionId { get; set; } // UserPermissionId (Primary key)

        [Display(Name = "User ID")]
        public int? UserId { get; set; } // UserId

        [Display(Name = "Permission ID")]
        public int? PermissionId { get; set; } // PermissionId

        // Foreign keys

        /// <summary>
        /// Parent Permission pointed by [UserPermission].([PermissionId]) (FK_UserPermission_Permission)
        /// </summary>
        public virtual Permission Permission { get; set; } // FK_UserPermission_Permission

        /// <summary>
        /// Parent User pointed by [UserPermission].([UserId]) (FK_UserPermission_User)
        /// </summary>
        public virtual User User { get; set; } // FK_UserPermission_User

        public UserPermission()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
