// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class UserMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
    {
        public UserMap()
            : this("dbo")
        {
        }

        public UserMap(string schema)
        {
            ToTable("User", schema);
            Property(x => x.UserId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsOptional();
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsOptional();
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar");
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar");
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit");
            Property(x => x.RoleId).HasColumnName(@"RoleId").HasColumnType("int");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.Users).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_User_GeneralBaseType
            HasRequired(a => a.Role).WithMany(b => b.Users).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_User_Role
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
