// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DebugMode
{

    // WorkBook
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class WorkBookMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkBook>
    {
        public WorkBookMap()
            : this("dbo")
        {
        }

        public WorkBookMap(string schema)
        {
            ToTable("WorkBook", schema);
            Property(x => x.WorkBookId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int");
            Property(x => x.TermId).HasColumnName(@"TermId").HasColumnType("int");
            Property(x => x.RankScore).HasColumnName(@"RankScore").HasColumnType("int");
            Property(x => x.AwardScore).HasColumnName(@"AwardScore").HasColumnType("int");
            Property(x => x.TotalScore).HasColumnName(@"TotalScore").HasColumnType("int");
            Property(x => x.RecordStatusId).HasColumnName(@"RecordStatusId").HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.GeneralBaseType).WithMany(b => b.WorkBooks).HasForeignKey(c => c.RecordStatusId).WillCascadeOnDelete(false); // FK_WorkBook_GeneralBaseType
            HasRequired(a => a.Student).WithMany(b => b.WorkBooks).HasForeignKey(c => c.StudentId).WillCascadeOnDelete(false); // FK_WorkBook_Student
            HasRequired(a => a.Term).WithMany(b => b.WorkBooks).HasForeignKey(c => c.TermId).WillCascadeOnDelete(false); // FK_WorkBook_Term
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
